//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancieraAmetrano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int cuentasID { get; set; }
        public Nullable<int> clientesID { get; set; }
        public Nullable<int> productosID { get; set; }
        public Nullable<int> monedasID { get; set; }
        public Nullable<double> saldo { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public Nullable<int> sucursalesID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
